# Generated by Django 3.1.5 on 2021-02-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_text',
        ),
    ]
