# Generated by Django 3.1.5 on 2021-02-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_auto_20210202_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='comment_db',
        ),
    ]
